### ISSUE TITLE
Display coordinates

### ISSUE THREAD

**Issue by StafDehat** [AndrewKvalheim/little-a-map#9]
When panning the map from one charted area of the world to another, distant, charted area - it's very easy to get lost in the black uncharted void.  An option to display coordinates on the map would be very helpful, either as lines of latitude/longitude, or just the current MousePos.

**Comment by AndrewKvalheim** [comment]
Thanks for this suggestion and #10, but the ability to get lost is a deliberate design goal of this project. You might prefer [Papyri](https://github.com/jason-green-io/papyri) which does reveal coordinates and allows a wider zoom.

**Comment by StafDehat** [comment]
Fair enough.  Thanks for the response!
